[package]
name = "nvn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvn-macro = { path = "./nvn-macro" }
bitflags = "1.2.1"
libc-nnsdk = { path = "../libc-nnsdk" }
nn = { path = "../nn" }